In [1]:
#input data

In [14]:
x <- 5

In [3]:
msg <- "hello world"

In [16]:
#evaluation

In [15]:
print (x)

[1] 5


In [8]:
print (x) + 1

[1] 5


[1] 6

In [17]:
msg

[1] "hello world"

In [18]:
#attributs

In [19]:
x <- 10:30

In [20]:
print (x)

 [1] 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30


In [21]:
class(x)

[1] "integer"

In [22]:
names(x)

NULL

In [23]:
length(x)

[1] 21

In [25]:
array(x)

[1] 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

In [34]:
#creating vectors

In [35]:
x <- c(0,5, 0,6)

In [36]:
print (x)

[1] 0 5 0 6


In [37]:
x <- vector("numeric", length=10)

In [38]:
print (x)

 [1] 0 0 0 0 0 0 0 0 0 0


In [39]:
y <- c(0.5, "abcd")

In [40]:
print (y)

[1] "0.5"  "abcd"


In [41]:
#explicit coercion

In [42]:
x <- 0:7

In [43]:
as.numeric(x)

[1] 0 1 2 3 4 5 6 7

In [44]:
as.logical(x)

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [45]:
as.character(x)

[1] "0" "1" "2" "3" "4" "5" "6" "7"

In [46]:
z <- c("1","2","3")

In [47]:
class(z)

[1] "character"

In [48]:
as.numeric(z)

[1] 1 2 3

In [49]:
#matrices

In [50]:
m <- matrix(1:6, nrow=2, ncol=3)

In [51]:
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [52]:
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [53]:
m <- 1:10

In [54]:
dim(m) <- c(2,5)

In [55]:
print(m)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [40]:
print(m[1])

[1] 1


In [42]:
print(m[0])

integer(0)


In [43]:
print(m[1:4])

[1] 1 2 3 4


In [63]:
#list

In [64]:
x <- list(1, "a", TRUE, 1 + 4i)

In [65]:
x[1]

[[1]]
[1] 1

In [66]:
x[3]

[[1]]
[1] TRUE

In [67]:
x[2:length(x)]

[[1]]
[1] "a"

[[2]]
[1] TRUE

[[3]]
[1] 1+4i

In [68]:
#factors

In [3]:
x <- factor(c("yes", "yes", "no", "yes", "no"))

In [4]:
print(x)

[1] yes yes no  yes no 
Levels: no yes


In [5]:
table(x)

x
 no yes 
  2   3 

In [6]:
unclass(x)

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"

In [9]:
print(unclass(x))

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"


In [14]:
x <- factor(c("yes", "yes", "no", "yes", "no"), levels = c("yes", "no"))


In [15]:
print(x)

[1] yes yes no  yes no 
Levels: yes no


In [16]:
#missing value

In [17]:
x <- c(1, 2, NA, 10, 3)

In [18]:
is.na(x)

[1] FALSE FALSE  TRUE FALSE FALSE

In [19]:
is.nan(x)

[1] FALSE FALSE FALSE FALSE FALSE

In [62]:
#read data

In [1]:
data <- read.csv("datasets/cluster/xclara.csv")

In [2]:
head(data)

X V1        V2       
1 1  2.072345 -3.241693
2 2 17.936710 15.784810
3 3  1.083576  7.319176
4 4 11.120670 14.406780
5 5 23.711550  2.557729
6 6 24.169930 32.024780

In [3]:
names(data)

[1] "X"  "V1" "V2"

In [4]:
tail(data)

X    V1       V2        
2995 2995 83.65175 -18.739220
2996 2996 85.65280  -6.461061
2997 2997 82.77088  -2.373299
2998 2998 64.46532 -10.501360
2999 2999 90.72282 -12.255840
3000 3000 64.87976 -24.877310

In [5]:
class(data)

[1] "data.frame"

In [6]:
str(data)

'data.frame':	3000 obs. of  3 variables:
 $ X : int  1 2 3 4 5 6 7 8 9 10 ...
 $ V1: num  2.07 17.94 1.08 11.12 23.71 ...
 $ V2: num  -3.24 15.78 7.32 14.41 2.56 ...


In [7]:
levels(data)

NULL

In [16]:
x <- data.frame(foo = 1:4, bar = c(T, T, F, F))

In [15]:
x <- data.frame(foo = 1:6, bar = c(T, T, F, F))

ERROR: Error in data.frame(foo = 1:6, bar = c(T, T, F, F)): arguments imply differing number of rows: 6, 4


In [17]:
x

foo bar  
1 1    TRUE
2 2    TRUE
3 3   FALSE
4 4   FALSE

In [18]:
print(x)

  foo   bar
1   1  TRUE
2   2  TRUE
3   3 FALSE
4   4 FALSE


In [19]:
nrow(x)

[1] 4

In [20]:
ncol(x)

[1] 2

In [21]:
#names

In [22]:
x <- 1:3

In [23]:
names(x)

NULL

In [24]:
names(x) <- c("v1", "v2", "v3")

In [25]:
x

v1 v2 v3 
 1  2  3

In [26]:
print(x)

v1 v2 v3 
 1  2  3 


In [27]:
names(x)

[1] "v1" "v2" "v3"

In [33]:
#names in list

In [29]:
x <- list("A"=1, "B"=2, "C"=3)

In [31]:
print(x)

$A
[1] 1

$B
[1] 2

$C
[1] 3



In [32]:
names(x)

[1] "A" "B" "C"

In [34]:
#names in matrics(both row and collumn)

In [2]:
m <- matrix(1:4, ncol=2, nrow=2)

In [4]:
m

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [5]:
names(m)

NULL

In [3]:
dimnames(m) <- list(c("A", "B"),c("AB", "BC"))

In [7]:
print(m)

  AB BC
A  1  3
B  2  4


In [8]:
row.names(m)

[1] "A" "B"

In [11]:
str(m)

 int [1:2, 1:2] 1 2 3 4
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:2] "A" "B"
  ..$ : chr [1:2] "AB" "BC"


In [4]:
names(m)

NULL

In [5]:
data <- read.csv("datasets/cluster/xclara.csv")

In [6]:
data <- read.csv('datasets/cluster/xclara.csv', stringsAsFactors=F)

In [7]:
head(data)

X V1        V2       
1 1  2.072345 -3.241693
2 2 17.936710 15.784810
3 3  1.083576  7.319176
4 4 11.120670 14.406780
5 5 23.711550  2.557729
6 6 24.169930 32.024780

In [10]:
str(data)

'data.frame':	3000 obs. of  3 variables:
 $ X : int  1 2 3 4 5 6 7 8 9 10 ...
 $ V1: num  2.07 17.94 1.08 11.12 23.71 ...
 $ V2: num  -3.24 15.78 7.32 14.41 2.56 ...


In [1]:
#using dput() and dump()

In [2]:
y <- data.frame(a = 1, b = "a")

In [3]:
dput(y)

structure(list(a = 1, b = structure(1L, .Label = "a", class = "factor")), .Names = c("a", 
"b"), row.names = c(NA, -1L), class = "data.frame")


In [4]:
y

a b
1 1 a

In [5]:
dput(y, file = "y.R")

In [6]:
new.y <- dget("y.R")

In [7]:
new.y

a b
1 1 a

In [8]:
x <- "foo"

In [9]:
y <- data.frame(a = 1L, b = "a")

In [13]:
dump(c("x", "y"), file = "data.R")

In [14]:
rm(x, y)

In [18]:
source("data.R")

In [20]:
str(y)

'data.frame':	1 obs. of  2 variables:
 $ a: int 1
 $ b: Factor w/ 1 level "a": 1


In [21]:
#binary format

In [22]:
a <- data.frame(x = rnorm(100), y = runif(100))

In [25]:
b <- c(3, 4.4, 1 / 3)

In [26]:
save(a, b, file = "mydata.rda")

In [29]:
Load("mydata.rda")

ERROR: Error in eval(expr, envir, enclos): could not find function "Load"


In [30]:
#Using Textual and Binary Formats for Storing Data

In [31]:
x <- list(1, 2, 3)

In [32]:
serialize(x, NULL)

 [1] 58 0a 00 00 00 02 00 03 03 02 00 02 03 00 00 00 00 13 00 00 00 03 00 00 00
[26] 0e 00 00 00 01 3f f0 00 00 00 00 00 00 00 00 00 0e 00 00 00 01 40 00 00 00
[51] 00 00 00 00 00 00 00 0e 00 00 00 01 40 08 00 00 00 00 00 00

In [33]:
#file connection

In [51]:
con <- file("datasets/cluster/xclara.csv")

In [46]:
print(con)

                  description                         class 
"datasets/cluster/xclara.csv"                        "file" 
                         mode                          text 
                          "r"                        "text" 
                       opened                      can read 
                     "closed"                         "yes" 
                    can write 
                        "yes" 


In [52]:
open(con, "r")

In [53]:
close(con)

In [54]:
#Reading Lines of a Text File

In [57]:
con <- file("datasets/cluster/xclara.csv")

In [58]:
x <- readLines(con, 10)

In [59]:
x

[1] "\"\",\"V1\",\"V2\""       "\"1\",2.072345,-3.241693"
 [3] "\"2\",17.93671,15.78481"  "\"3\",1.083576,7.319176" 
 [5] "\"4\",11.12067,14.40678"  "\"5\",23.71155,2.557729" 
 [7] "\"6\",24.16993,32.02478"  "\"7\",21.66578,4.892855" 
 [9] "\"8\",4.693684,12.34217"  "\"9\",19.21191,-1.121366"

In [60]:
#Reading From a URL Connection

In [74]:
# con <- url("http://www.jhsph.edu", "r")

In [75]:
# x <- readLines(con)

In [76]:
# head(x)

In [77]:
#########

In [78]:
#subsetting vector

In [79]:
x <- c("a", "b", "c", "c", "d", "a")

In [80]:
x[1]

[1] "a"

In [81]:
x[2:4]

[1] "b" "c" "c"

In [82]:
x[c(1, 3, 4)]

[1] "a" "c" "c"

In [1]:
#subsetting matrix

In [2]:
x <- matrix(1:6, 2,3)

In [4]:
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [5]:
x[1, 2]

[1] 3

In [6]:
x[2,2]

[1] 4

In [7]:
x[1,]

[1] 1 3 5

In [8]:
x[,1]

[1] 1 2

In [9]:
x[2,]

[1] 2 4 6

In [10]:
x[,2]

[1] 3 4

In [11]:
#Dropping matrix dimensions

In [12]:
x <- matrix(1:6, 2, 3)

In [14]:
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [13]:
x[1,2]

[1] 3

In [18]:
x[1, 2, drop = FALSE]

[,1]
[1,] 3

In [19]:
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [20]:
#Subsetting Lists

In [25]:
x <- list(foo = 1:4, bar = 0.6)

In [26]:
print(x)

$foo
[1] 1 2 3 4

$bar
[1] 0.6



In [27]:
x[1]

$foo
[1] 1 2 3 4

In [28]:
x["bar"]

$bar
[1] 0.6

In [29]:
x$bar

[1] 0.6

In [30]:
x$foo

[1] 1 2 3 4

In [31]:
#Subsetting Nested Elements of a List

In [32]:
x <- list(a = list(10, 12, 14), b = c(3.14, 2.81))

In [35]:
x

$a
$a[[1]]
[1] 10

$a[[2]]
[1] 12

$a[[3]]
[1] 14


$b
[1] 3.14 2.81

In [34]:
x[[c(1, 3)]]

[1] 14

In [36]:
x[[1]][[3]]

[1] 14

In [37]:
x[[c(2, 1)]]

[1] 3.14

In [1]:
#extracting multiple elements of list

In [2]:
x <- list(foo = 1:4, bar = 0.6, baz = "hello")

In [3]:
x[c(1, 3)]

$foo
[1] 1 2 3 4

$baz
[1] "hello"

In [7]:
#partial matching

In [4]:
x <- list(aardvark = 1:5)

In [5]:
x

$aardvark
[1] 1 2 3 4 5

In [6]:
x$aa

[1] 1 2 3 4 5

In [9]:
x$aard

[1] 1 2 3 4 5

In [10]:
x[["a", exact = FALSE]]

[1] 1 2 3 4 5

In [11]:
#remove N/A value

In [12]:
x <- c(1, 2, NA, 4, NA, 5)

In [13]:
xx <- is.na(x)

In [14]:
xx

[1] FALSE FALSE  TRUE FALSE  TRUE FALSE

In [15]:
x[!xx]

[1] 1 2 4 5

In [16]:
x <- c(1, 2, NA, 4, NA, 5)

In [17]:
y <- c("a", "b", NA, "d", NA, "f")

In [18]:
xy <- complete.cases(x, y)

In [19]:
xy

[1]  TRUE  TRUE FALSE  TRUE FALSE  TRUE

In [20]:
x[xy]

[1] 1 2 4 5

In [21]:
y[xy]

[1] "a" "b" "d" "f"

In [22]:
#vectorized operations

In [23]:
x <- 1:4

In [24]:
y <- 6:9

In [25]:
z <- x + y

In [26]:
z

[1]  7  9 11 13

In [27]:
z <- numeric(length(x))
for(i in seq_along(x)) {
z <- x[i] + y[i]
}

In [28]:
z

[1] 13

In [29]:
x <- 1:4

In [30]:
x < 2

[1]  TRUE FALSE FALSE FALSE

In [1]:
#vectorized matrix operation

In [2]:
x <- matrix(1:4, 2, 2)

In [3]:
print(x)

     [,1] [,2]
[1,]    1    3
[2,]    2    4


In [4]:
y <- matrix(rep(10, 4), 2, 2)

In [5]:
print(y)

     [,1] [,2]
[1,]   10   10
[2,]   10   10


In [6]:
x * y

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [7]:
x %*% y

[,1] [,2]
[1,] 40   40  
[2,] 60   60

In [8]:
#dates and time

In [9]:
x <- as.Date("1990-06-14")

In [10]:
print(x)

[1] "1990-06-14"


In [11]:
unclass(x)

[1] 7469

In [12]:
print(x)

[1] "1990-06-14"


In [13]:
x <- Sys.time()

In [14]:
print(x)

[1] "2017-12-27 02:49:57 UTC"


In [15]:
class(x)

[1] "POSIXct" "POSIXt"

In [16]:
p <- as.POSIXlt(x)

In [17]:
p

[1] "2017-12-27 02:49:57 UTC"

In [18]:
names(unclass(p))

[1] "sec"    "min"    "hour"   "mday"   "mon"    "year"   "wday"   "yday"  
 [9] "isdst"  "zone"   "gmtoff"

In [19]:
p$wday

[1] 3

In [20]:
p$sec

[1] 57.32635

In [21]:
datestring <- c("January 10, 2012 10:40", "December 9, 2011 9:10")

In [22]:
x <- strptime(datestring, "%B %d, %Y %H:%M")

In [23]:
x

[1] "2012-01-10 10:40:00 UTC" "2011-12-09 09:10:00 UTC"

In [24]:
class(x)

[1] "POSIXlt" "POSIXt"

In [25]:
#operation on date and time

In [33]:
x <- as.Date("2012-01-01")

In [34]:
x

[1] "2012-01-01"

In [31]:
y <- strptime("9 Jan 2011 11:34:21", "%d %b %Y %H:%M:%S")

In [32]:
y

[1] "2011-01-09 11:34:21 UTC"

In [28]:
x-y

Warning message in eval(expr, envir, enclos):
“Incompatible methods ("-.Date", "-.POSIXt") for "-"”

ERROR: Error in x - y: non-numeric argument to binary operator


In [29]:
x <- as.POSIXlt(x)

In [30]:
x-y

Time difference of 356.5178 days

In [1]:
#managing data frames with the dplyr package

In [8]:
library(dplyr)


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



In [9]:
x <- read.csv("datasets/cluster/xclara.csv")

In [10]:
head(x)

X V1        V2       
1 1  2.072345 -3.241693
2 2 17.936710 15.784810
3 3  1.083576  7.319176
4 4 11.120670 14.406780
5 5 23.711550  2.557729
6 6 24.169930 32.024780

In [7]:
#convert to dplyr data table

In [8]:
xs <- tbl_df(x)

In [9]:
print(xs)

# A tibble: 3,000 x 3
       X        V1        V2
   <int>     <dbl>     <dbl>
 1     1  2.072345 -3.241693
 2     2 17.936710 15.784810
 3     3  1.083576  7.319176
 4     4 11.120670 14.406780
 5     5 23.711550  2.557729
 6     6 24.169930 32.024780
 7     7 21.665780  4.892855
 8     8  4.693684 12.342170
 9     9 19.211910 -1.121366
10    10  4.230391 -4.441536
# ... with 2,990 more rows


In [17]:
dim(xs)

[1] 3000    3

In [18]:
dim(x)

[1] 3000    3

In [19]:
str(xs)

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	3000 obs. of  3 variables:
 $ X : int  1 2 3 4 5 6 7 8 9 10 ...
 $ V1: num  2.07 17.94 1.08 11.12 23.71 ...
 $ V2: num  -3.24 15.78 7.32 14.41 2.56 ...


In [22]:
names(xs)[2:3]

[1] "V1" "V2"

In [25]:
subset <- select(xs, V1:V2)

In [26]:
head(subset)

V1        V2       
1  2.072345 -3.241693
2 17.936710 15.784810
3  1.083576  7.319176
4 11.120670 14.406780
5 23.711550  2.557729
6 24.169930 32.024780

In [32]:
print(select(xs, -(V1:X)))

# A tibble: 3,000 x 1
          V2
       <dbl>
 1 -3.241693
 2 15.784810
 3  7.319176
 4 14.406780
 5  2.557729
 6 32.024780
 7  4.892855
 8 12.342170
 9 -1.121366
10 -4.441536
# ... with 2,990 more rows


In [28]:
subset <- select(xs, starts_with("V"))

In [29]:
str(subset)

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	3000 obs. of  2 variables:
 $ V1: num  2.07 17.94 1.08 11.12 23.71 ...
 $ V2: num  -3.24 15.78 7.32 14.41 2.56 ...


In [34]:
subset <- select(xs, ends_with("2"))

In [35]:
str(subset)

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	3000 obs. of  1 variable:
 $ V2: num  -3.24 15.78 7.32 14.41 2.56 ...


In [31]:
##filter

In [36]:
fltr <- filter(xs, V2 > 20)

In [37]:
str(fltr)

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1303 obs. of  3 variables:
 $ X : int  6 11 16 19 21 23 30 56 66 67 ...
 $ V1: num  24.17 9.13 4.42 8.19 18.77 ...
 $ V2: num  32 23.6 22.8 28.1 24.2 ...


In [38]:
summary(fltr$V2)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  20.08   49.79   58.25   55.69   65.41   87.31 

In [10]:
fltr <- filter(xs, V1 > 30 & V2 > 20)

In [11]:
print(fltr)

# A tibble: 973 x 3
       X       V1       V2
   <int>    <dbl>    <dbl>
 1    71 31.40462 26.77209
 2   182 32.74222 25.56641
 3   280 30.69195 21.91320
 4   327 37.48364 34.12808
 5   610 39.89024 23.99687
 6   901 48.19050 56.00667
 7   902 48.32863 76.09440
 8   903 31.44145 62.66712
 9   904 37.60916 64.75492
10   905 52.68577 71.53609
# ... with 963 more rows


In [30]:
##select

In [13]:
print(select(fltr, X, V2))

# A tibble: 973 x 2
       X       V2
   <int>    <dbl>
 1    71 26.77209
 2   182 25.56641
 3   280 21.91320
 4   327 34.12808
 5   610 23.99687
 6   901 56.00667
 7   902 76.09440
 8   903 62.66712
 9   904 64.75492
10   905 71.53609
# ... with 963 more rows


In [32]:
##arrange

In [15]:
xs <- arrange(xs, X)

In [16]:
head(select(xs, X, V2), 3)

X V2       
1 1 -3.241693
2 2 15.784810
3 3  7.319176

In [21]:
tail(select(xs, X, V1), 3)

X    V1      
1 2998 64.46532
2 2999 90.72282
3 3000 64.87976

In [23]:
head(xs[, 1:3], 3)

X V1        V2       
1 1  2.072345 -3.241693
2 2 17.936710 15.784810
3 3  1.083576  7.319176

In [33]:
##rename

In [24]:
xs <- rename(xs, No = X, D1 = V1, D2 = V2)

In [28]:
head(xs[, 1:3], 3)

No D1        D2       
1 1   2.072345 -3.241693
2 2  17.936710 15.784810
3 3   1.083576  7.319176

In [34]:
##mutate

In [35]:
xs <- mutate(xs, Dtrend = D2 - mean(D1, na.rm = TRUE))

In [36]:
print(head(xs))

# A tibble: 6 x 4
     No        D1        D2     Dtrend
  <int>     <dbl>     <dbl>      <dbl>
1     1  2.072345 -3.241693 -43.853051
2     2 17.936710 15.784810 -24.826548
3     3  1.083576  7.319176 -33.292182
4     4 11.120670 14.406780 -26.204578
5     5 23.711550  2.557729 -38.053629
6     6 24.169930 32.024780  -8.586578


In [1]:
##group_by

In [2]:
dt <- read.csv("datasets/datasets/InsectSprays.csv")

In [3]:
library(dplyr)


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



In [4]:
dts <- tbl_df(dt)

In [5]:
print(head(dts))

# A tibble: 6 x 3
      X count  spray
  <int> <int> <fctr>
1     1    10      A
2     2     7      A
3     3    20      A
4     4    14      A
5     5    14      A
6     6    12      A


In [15]:
spry <- group_by(dts, spray)

In [16]:
print(spry)

# A tibble: 72 x 3
# Groups:   spray [6]
       X count  spray
   <int> <int> <fctr>
 1     1    10      A
 2     2     7      A
 3     3    20      A
 4     4    14      A
 5     5    14      A
 6     6    12      A
 7     7    10      A
 8     8    23      A
 9     9    17      A
10    10    20      A
# ... with 62 more rows


In [27]:
summarize(spry)

spray
1 A    
2 B    
3 C    
4 D    
5 E    
6 F

In [21]:
summary(spry)

       X             count       spray 
 Min.   : 1.00   Min.   : 0.00   A:12  
 1st Qu.:18.75   1st Qu.: 3.00   B:12  
 Median :36.50   Median : 7.00   C:12  
 Mean   :36.50   Mean   : 9.50   D:12  
 3rd Qu.:54.25   3rd Qu.:14.25   E:12  
 Max.   :72.00   Max.   :26.00   F:12  

In [32]:
##pipeline operater %>%

In [33]:
#Control Structures

In [1]:
##if_else

In [8]:
x <- 1:3

In [15]:
x <- runif(1, 2, 10)
if(x > 3) {
y <- 10
} else {
y <- 0
}

In [16]:
a <- c(5,7,2,9)

In [17]:
ifelse(a %% 2 == 0,"even","odd")

[1] "odd"  "odd"  "even" "odd"

In [18]:
##for_loop

In [1]:
for (i in 1:10){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [2]:
x <- c(2,5,3,9,8,11,6)
count <- 0
for (val in x) {
    if(val %% 2 == 0)  count = count+1
}
print(count)

[1] 3


In [3]:
x <- c("a", "b", "c")

In [5]:
for (Letter in x){
    print(Letter)
}

[1] "a"
[1] "b"
[1] "c"


In [6]:
##nested for_lop

In [7]:
x <- matrix(1:6, 2,3)
    for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
        print(x[i, j])
    }
}

[1] 1
[1] 3
[1] 5
[1] 2
[1] 4
[1] 6


In [8]:
##while_loops

In [9]:
count <- 0
while (count < 10){
    print(count)
    count <- count + 1
}

[1] 0
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9


In [10]:
z <- 5

In [11]:
set.seed(1)

In [12]:
while(z >= 3 && z <= 10) {
 coin <- rbinom(1, 1, 0.5)
 if(coin == 1) { ## random walk
    z <- z + 1
} else {
    z <- z - 1
    }
}

In [13]:
print(z)

[1] 2


In [14]:
##repeat_loops

In [15]:
x0 <- 1

In [16]:
tol <- 1e-8

In [17]:
repeat {
    x1 <- computeEstimate()
    if(abs(x1 - x0) < tol) { ## Close enough?
        break
    } else {
        x0 <- x1
    }
}

ERROR: Error: could not find function "computeEstimate"


In [18]:
#Note that the above code will not run if the computeEstimate() function is not defined (I just made 
#it up for the purposes of this demonstration).

In [19]:
x <- 1:5

In [20]:
for (val in x){
    if (val == 3){
        break
    }
    print(val)
}

[1] 1
[1] 2


In [22]:
##next_break

In [23]:
x <- 1:5

In [24]:
for (val in x){
    if (val == 3){
        next
    }
    print(val)
}

[1] 1
[1] 2
[1] 4
[1] 5


In [25]:
#functions

In [26]:
f <- function(){
    cat("Hello World!\n")
}

In [28]:
f()

Hello World!


In [29]:
class(f)

[1] "function"

In [32]:
pwr <- function(x, y){
    result <- x^y
    print(paste(x,"raised to the power", y, "is", result))
}

In [33]:
pwr(2,3)

[1] "2 raised to the power 3 is 8"


In [34]:
##default value arguments

In [35]:
pwr <- function(x, y=3){
    result <- x^y
    print(paste(x,"raised to the power", y, "is", result))
}

In [36]:
pwr(2)

[1] "2 raised to the power 3 is 8"


In [37]:
##the ... arguments

In [49]:
addPercent <- function(x, mult = 100, ...){
    
    percent <- round(x * mult, ...)
    paste(percent, "%", sep = )
}

In [52]:
addPercent(1, digits = 2)

[1] "100 %"

In [53]:
addPercent(10, digits = 2)

[1] "1000 %"

In [54]:
#scooping rules of R

In [55]:
f <- function(){
    x * x
}

In [57]:
f

function(){
    x * x
}

In [58]:
search()

[1] ".GlobalEnv"        "jupyter:irkernel"  "jupyter:irkernel" 
 [4] "package:stats"     "package:graphics"  "package:grDevices"
 [7] "package:utils"     "package:datasets"  "package:methods"  
[10] "Autoloads"         "package:base"

In [59]:
outer_func <- function(){
   a <- 20
   inner_func <- function(){
       a <- 30
       print(a)
   }
   inner_func()
   print(a)
}

In [60]:
a <- 10

In [61]:
outer_func()

[1] 30
[1] 20


In [63]:
print(a)

[1] 10


In [1]:
#coding standart for R

In [2]:
##lapply

In [3]:
lapply

function (X, FUN, ...) 
{
    FUN <- match.fun(FUN)
    if (!is.vector(X) || is.object(X)) 
        X <- as.list(X)
    .Internal(lapply(X, FUN))
}
<bytecode: 0x1b767f0>
<environment: namespace:base>

In [4]:
x <- list(a = 1:5, b = rnorm(10))

In [5]:
lapply(x, mean)

$a
[1] 3

$b
[1] -0.5953007

In [6]:
x <- list(a = 1:4, b = rnorm(10), c = rnorm(20, 1), d = rnorm(100, 5))

In [7]:
lapply(x, mean)

$a
[1] 2.5

$b
[1] 0.1526944

$c
[1] 1.200724

$d
[1] 4.987604

In [8]:
##sapply

In [9]:
x <- list(a = 1:4, b = rnorm(10), c = rnorm(20, 1), d = rnorm(100, 5))

In [10]:
sapply(x, mean)

a          b          c          d 
 2.5000000 -0.2426530  0.9195612  4.8816927

In [11]:
##split

In [12]:
str(split)

function (x, f, drop = FALSE, ...)  


In [13]:
x <- 1:3

In [14]:
y <- c("a", "b", "c")

In [17]:
split(x, y)

$a
[1] 1

$b
[1] 2

$c
[1] 3

In [18]:
library(datasets)

In [19]:
head(airquality)

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [20]:
s <- split(airquality, airquality$Month)

In [21]:
head(airquality)

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [24]:
str(s)

List of 5
 $ 5:'data.frame':	31 obs. of  6 variables:
  ..$ Ozone  : int [1:31] 41 36 12 18 NA 28 23 19 8 NA ...
  ..$ Solar.R: int [1:31] 190 118 149 313 NA NA 299 99 19 194 ...
  ..$ Wind   : num [1:31] 7.4 8 12.6 11.5 14.3 14.9 8.6 13.8 20.1 8.6 ...
  ..$ Temp   : int [1:31] 67 72 74 62 56 66 65 59 61 69 ...
  ..$ Month  : int [1:31] 5 5 5 5 5 5 5 5 5 5 ...
  ..$ Day    : int [1:31] 1 2 3 4 5 6 7 8 9 10 ...
 $ 6:'data.frame':	30 obs. of  6 variables:
  ..$ Ozone  : int [1:30] NA NA NA NA NA NA 29 NA 71 39 ...
  ..$ Solar.R: int [1:30] 286 287 242 186 220 264 127 273 291 323 ...
  ..$ Wind   : num [1:30] 8.6 9.7 16.1 9.2 8.6 14.3 9.7 6.9 13.8 11.5 ...
  ..$ Temp   : int [1:30] 78 74 67 84 85 79 82 87 90 87 ...
  ..$ Month  : int [1:30] 6 6 6 6 6 6 6 6 6 6 ...
  ..$ Day    : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
 $ 7:'data.frame':	31 obs. of  6 variables:
  ..$ Ozone  : int [1:31] 135 49 32 NA 64 40 77 97 97 85 ...
  ..$ Solar.R: int [1:31] 269 248 236 101 175 314 276 267 272 175 ...
  

In [25]:
##tapply

In [26]:
str(tapply)

function (X, INDEX, FUN = NULL, ..., simplify = TRUE)  


In [27]:
x <- c(rnorm(10), runif(10), rnorm(10, 1))

In [31]:
y <- gl(3, 10)

In [32]:
tapply(x, y, mean)

1            2            3 
-0.005724629  0.534365613  1.264415074

In [33]:
##apply

In [34]:
x <- matrix(rnorm(200), 20, 10)

In [38]:
head(x, 3)

[,1]      [,2]       [,3]       [,4]       [,5]       [,6]      
[1,] -1.035738 -0.9680937 -0.4235609  0.4373896 0.08423062 -0.9654401
[2,] -1.121299 -1.5816640 -1.5793554 -0.4138297 0.29243294 -1.0535999
[3,] -2.155960  0.8879521  1.7123511 -0.5850723 0.59208546  0.9660446
     [,7]        [,8]       [,9]       [,10]     
[1,]  0.44268350 -0.8524732 -1.0511728 -0.6931106
[2,]  0.04905038 -2.4264809 -0.6923437  0.8106667
[3,] -0.80681009  0.2537708  0.2974877 -1.0202878

In [35]:
apply(x, 2, mean)

[1] -0.31401050  0.03259909 -0.29662716 -0.18140787  0.30250722 -0.13608482
 [7] -0.22228858 -0.23477658  0.10077248 -0.19983067

In [45]:
##col/row sums and means

In [40]:
a <- array(rnorm(2 * 2 * 10), c(2, 2, 10))

In [41]:
apply(a, c(1, 2), mean)

[,1]       [,2]       
[1,]  0.2182181 -0.03601413
[2,] -0.1434766  0.36452723

In [42]:
rowMeans(a, dims = 2)

[,1]       [,2]       
[1,]  0.2182181 -0.03601413
[2,] -0.1434766  0.36452723

In [43]:
colMeans(a, dims = 2)

[1]  0.33185288  0.09656356  0.06360079  0.05078353  0.26799414 -0.26816533
 [7] -0.33682519  0.28093208 -0.23784163  0.75924170

In [44]:
##mapply

In [46]:
str(mapply)

function (FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)  


In [47]:
mapply(rep, 1:4, 4:1)

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

In [48]:
#vectorizing a function

In [53]:
sumsq <- function(mu, sigma, x) {
 sum(((x - mu) / sigma)^2)
}

In [54]:
x <- rnorm(100)

In [56]:
sumsq(1:10, 1:10, x)

[1] 112.8739

In [59]:
#debugging

In [61]:
log(-1)

Warning message in log(-1):
“NaNs produced”

[1] NaN

In [62]:
##traceback

In [73]:
mean(u)

ERROR: Error in mean(u): object 'u' not found


In [81]:
# end
# Basic R Programming
# ref: https://www.cs.upc.edu/~robert/teaching/estadistica/rprogramming.pdf