In [1]:
#input data

In [14]:
x <- 5

In [3]:
msg <- "hello world"

In [16]:
#evaluation

In [15]:
print (x)

[1] 5


In [8]:
print (x) + 1

[1] 5


[1] 6

In [17]:
msg

[1] "hello world"

In [18]:
#attributs

In [19]:
x <- 10:30

In [20]:
print (x)

 [1] 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30


In [21]:
class(x)

[1] "integer"

In [22]:
names(x)

NULL

In [23]:
length(x)

[1] 21

In [25]:
array(x)

[1] 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30

In [34]:
#creating vectors

In [35]:
x <- c(0,5, 0,6)

In [36]:
print (x)

[1] 0 5 0 6


In [37]:
x <- vector("numeric", length=10)

In [38]:
print (x)

 [1] 0 0 0 0 0 0 0 0 0 0


In [39]:
y <- c(0.5, "abcd")

In [40]:
print (y)

[1] "0.5"  "abcd"


In [41]:
#explicit coercion

In [42]:
x <- 0:7

In [43]:
as.numeric(x)

[1] 0 1 2 3 4 5 6 7

In [44]:
as.logical(x)

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [45]:
as.character(x)

[1] "0" "1" "2" "3" "4" "5" "6" "7"

In [46]:
z <- c("1","2","3")

In [47]:
class(z)

[1] "character"

In [48]:
as.numeric(z)

[1] 1 2 3

In [49]:
#matrices

In [50]:
m <- matrix(1:6, nrow=2, ncol=3)

In [51]:
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [52]:
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [53]:
m <- 1:10

In [54]:
dim(m) <- c(2,5)

In [55]:
print(m)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [40]:
print(m[1])

[1] 1


In [42]:
print(m[0])

integer(0)


In [43]:
print(m[1:4])

[1] 1 2 3 4


In [63]:
#list

In [64]:
x <- list(1, "a", TRUE, 1 + 4i)

In [65]:
x[1]

[[1]]
[1] 1

In [66]:
x[3]

[[1]]
[1] TRUE

In [67]:
x[2:length(x)]

[[1]]
[1] "a"

[[2]]
[1] TRUE

[[3]]
[1] 1+4i

In [68]:
#factors

In [3]:
x <- factor(c("yes", "yes", "no", "yes", "no"))

In [4]:
print(x)

[1] yes yes no  yes no 
Levels: no yes


In [5]:
table(x)

x
 no yes 
  2   3 

In [6]:
unclass(x)

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"

In [9]:
print(unclass(x))

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"


In [14]:
x <- factor(c("yes", "yes", "no", "yes", "no"), levels = c("yes", "no"))


In [15]:
print(x)

[1] yes yes no  yes no 
Levels: yes no


In [16]:
#missing value

In [17]:
x <- c(1, 2, NA, 10, 3)

In [18]:
is.na(x)

[1] FALSE FALSE  TRUE FALSE FALSE

In [19]:
is.nan(x)

[1] FALSE FALSE FALSE FALSE FALSE

In [62]:
#read data

In [1]:
data <- read.csv("datasets/cluster/xclara.csv")

In [2]:
print(data)

        X           V1            V2
1       1   2.07234500  -3.241693000
2       2  17.93671000  15.784810000
3       3   1.08357600   7.319176000
4       4  11.12067000  14.406780000
5       5  23.71155000   2.557729000
6       6  24.16993000  32.024780000
7       7  21.66578000   4.892855000
8       8   4.69368400  12.342170000
9       9  19.21191000  -1.121366000
10     10   4.23039100  -4.441536000
11     11   9.12713000  23.605720000
12     12   0.40750310  15.297050000
13     13   7.31484600   3.309312000
14     14  -3.43840300 -12.025270000
15     15  17.63935000  -3.212345000
16     16   4.41529200  22.815550000
17     17  11.94122000   8.122487000
18     18   0.72585320   1.806819000
19     19   8.18527300  28.132600000
20     20  -5.77358700   1.024800000
21     21  18.76943000  24.169460000
22     22   7.75201600  -3.334991000
23     23  10.61132000  28.443780000
24     24   2.02165000  -4.687122000
25     25   5.14552500  11.186000000
26     26   6.24331000  19.477160000
2

In [3]:
names(data)

[1] "X"  "V1" "V2"

In [4]:
row.names(data)

[1] "1"    "2"    "3"    "4"    "5"    "6"    "7"    "8"    "9"    "10"  
  [11] "11"   "12"   "13"   "14"   "15"   "16"   "17"   "18"   "19"   "20"  
  [21] "21"   "22"   "23"   "24"   "25"   "26"   "27"   "28"   "29"   "30"  
  [31] "31"   "32"   "33"   "34"   "35"   "36"   "37"   "38"   "39"   "40"  
  [41] "41"   "42"   "43"   "44"   "45"   "46"   "47"   "48"   "49"   "50"  
  [51] "51"   "52"   "53"   "54"   "55"   "56"   "57"   "58"   "59"   "60"  
  [61] "61"   "62"   "63"   "64"   "65"   "66"   "67"   "68"   "69"   "70"  
  [71] "71"   "72"   "73"   "74"   "75"   "76"   "77"   "78"   "79"   "80"  
  [81] "81"   "82"   "83"   "84"   "85"   "86"   "87"   "88"   "89"   "90"  
  [91] "91"   "92"   "93"   "94"   "95"   "96"   "97"   "98"   "99"   "100" 
 [101] "101"  "102"  "103"  "104"  "105"  "106"  "107"  "108"  "109"  "110" 
 [111] "111"  "112"  "113"  "114"  "115"  "116"  "117"  "118"  "119"  "120" 
 [121] "121"  "122"  "123"  "124"  "125"  "126"  "127"  "128"  "129"  "130" 
 [131] "131"  "132"  "133"  "134"  "135"  "136"  "137"  "138"  "139"  "140" 
 [141] "141"  "142"  "143"  "144"  "145"  "146"  "147"  "148"  "149"  "150" 
 [151] "151"  "152"  "153"  "154"  "155"  "156"  "157"  "158"  "159"  "160" 
 [161] "161"  "162"  "163"  "164"  "165"  "166"  "167"  "168"  "169"  "170" 
 [171] "171"  "172"  "173"  "174"  "175"  "176"  "177"  "178"  "179"  "180" 
 [181] "181"  "182"  "183"  "184"  "185"  "186"  "187"  "188"  "189"  "190" 
 [191] "191"  "192"  "193"  "194"  "195"  "196"  "197"  "198"  "199"  "200" 
 [201] "201"  "202"  "203"  "204"  "205"  "206"  "207"  "208"  "209"  "210" 
 [211] "211"  "212"  "213"  "214"  "215"  "216"  "217"  "218"  "219"  "220" 
 [221] "221"  "222"  "223"  "224"  "225"  "226"  "227"  "228"  "229"  "230" 
 [231] "231"  "232"  "233"  "234"  "235"  "236"  "237"  "238"  "239"  "240" 
 [241] "241"  "242"  "243"  "244"  "245"  "246"  "247"  "248"  "249"  "250" 
 [251] "251"  "252"  "253"  "254"  "255"  "256"  "257"  "258"  "259"  "260" 
 [261] "261"  "262"  "263"  "264"  "265"  "266"  "267"  "268"  "269"  "270" 
 [271] "271"  "272"  "273"  "274"  "275"  "276"  "277"  "278"  "279"  "280" 
 [281] "281"  "282"  "283"  "284"  "285"  "286"  "287"  "288"  "289"  "290" 
 [291] "291"  "292"  "293"  "294"  "295"  "296"  "297"  "298"  "299"  "300" 
 [301] "301"  "302"  "303"  "304"  "305"  "306"  "307"  "308"  "309"  "310" 
 [311] "311"  "312"  "313"  "314"  "315"  "316"  "317"  "318"  "319"  "320" 
 [321] "321"  "322"  "323"  "324"  "325"  "326"  "327"  "328"  "329"  "330" 
 [331] "331"  "332"  "333"  "334"  "335"  "336"  "337"  "338"  "339"  "340" 
 [341] "341"  "342"  "343"  "344"  "345"  "346"  "347"  "348"  "349"  "350" 
 [351] "351"  "352"  "353"  "354"  "355"  "356"  "357"  "358"  "359"  "360" 
 [361] "361"  "362"  "363"  "364"  "365"  "366"  "367"  "368"  "369"  "370" 
 [371] "371"  "372"  "373"  "374"  "375"  "376"  "377"  "378"  "379"  "380" 
 [381] "381"  "382"  "383"  "384"  "385"  "386"  "387"  "388"  "389"  "390" 
 [391] "391"  "392"  "393"  "394"  "395"  "396"  "397"  "398"  "399"  "400" 
 [401] "401"  "402"  "403"  "404"  "405"  "406"  "407"  "408"  "409"  "410" 
 [411] "411"  "412"  "413"  "414"  "415"  "416"  "417"  "418"  "419"  "420" 
 [421] "421"  "422"  "423"  "424"  "425"  "426"  "427"  "428"  "429"  "430" 
 [431] "431"  "432"  "433"  "434"  "435"  "436"  "437"  "438"  "439"  "440" 
 [441] "441"  "442"  "443"  "444"  "445"  "446"  "447"  "448"  "449"  "450" 
 [451] "451"  "452"  "453"  "454"  "455"  "456"  "457"  "458"  "459"  "460" 
 [461] "461"  "462"  "463"  "464"  "465"  "466"  "467"  "468"  "469"  "470" 
 [471] "471"  "472"  "473"  "474"  "475"  "476"  "477"  "478"  "479"  "480" 
 [481] "481"  "482"  "483"  "484"  "485"  "486"  "487"  "488"  "489"  "490" 
 [491] "491"  "492"  "493"  "494"  "495"  "496"  "497"  "498"  "499"  "500" 
 [501] "501"  "502"  "503"  "504"  "505"  "506"  "507"  "508"  "509"  "510" 
 [511] "511"  "512"  "513"  "514"  "515"  "516"  "517"  "518"  "519"  "520" 

In [5]:
class(data)

[1] "data.frame"

In [6]:
str(data)

'data.frame':	3000 obs. of  3 variables:
 $ X : int  1 2 3 4 5 6 7 8 9 10 ...
 $ V1: num  2.07 17.94 1.08 11.12 23.71 ...
 $ V2: num  -3.24 15.78 7.32 14.41 2.56 ...


In [7]:
levels(data)

NULL

In [16]:
x <- data.frame(foo = 1:4, bar = c(T, T, F, F))

In [15]:
x <- data.frame(foo = 1:6, bar = c(T, T, F, F))

ERROR: Error in data.frame(foo = 1:6, bar = c(T, T, F, F)): arguments imply differing number of rows: 6, 4


In [17]:
x

foo bar  
1 1    TRUE
2 2    TRUE
3 3   FALSE
4 4   FALSE

In [18]:
print(x)

  foo   bar
1   1  TRUE
2   2  TRUE
3   3 FALSE
4   4 FALSE


In [19]:
nrow(x)

[1] 4

In [20]:
ncol(x)

[1] 2

In [21]:
#names

In [22]:
x <- 1:3

In [23]:
names(x)

NULL

In [24]:
names(x) <- c("v1", "v2", "v3")

In [25]:
x

v1 v2 v3 
 1  2  3

In [26]:
print(x)

v1 v2 v3 
 1  2  3 


In [27]:
names(x)

[1] "v1" "v2" "v3"

In [33]:
#names in list

In [29]:
x <- list("A"=1, "B"=2, "C"=3)

In [31]:
print(x)

$A
[1] 1

$B
[1] 2

$C
[1] 3



In [32]:
names(x)

[1] "A" "B" "C"

In [34]:
#names in matrics(both row and collumn)

In [2]:
m <- matrix(1:4, ncol=2, nrow=2)

In [4]:
m

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [5]:
names(m)

NULL

In [3]:
dimnames(m) <- list(c("A", "B"),c("AB", "BC"))

In [7]:
print(m)

  AB BC
A  1  3
B  2  4


In [8]:
row.names(m)

[1] "A" "B"

In [11]:
str(m)

 int [1:2, 1:2] 1 2 3 4
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:2] "A" "B"
  ..$ : chr [1:2] "AB" "BC"


In [4]:
names(m)

NULL

In [5]:
data <- read.csv("datasets/cluster/xclara.csv")

In [8]:
data <- read.csv('datasets/cluster/xclara.csv', stringsAsFactors=F)

In [9]:
print(data)

        X           V1            V2
1       1   2.07234500  -3.241693000
2       2  17.93671000  15.784810000
3       3   1.08357600   7.319176000
4       4  11.12067000  14.406780000
5       5  23.71155000   2.557729000
6       6  24.16993000  32.024780000
7       7  21.66578000   4.892855000
8       8   4.69368400  12.342170000
9       9  19.21191000  -1.121366000
10     10   4.23039100  -4.441536000
11     11   9.12713000  23.605720000
12     12   0.40750310  15.297050000
13     13   7.31484600   3.309312000
14     14  -3.43840300 -12.025270000
15     15  17.63935000  -3.212345000
16     16   4.41529200  22.815550000
17     17  11.94122000   8.122487000
18     18   0.72585320   1.806819000
19     19   8.18527300  28.132600000
20     20  -5.77358700   1.024800000
21     21  18.76943000  24.169460000
22     22   7.75201600  -3.334991000
23     23  10.61132000  28.443780000
24     24   2.02165000  -4.687122000
25     25   5.14552500  11.186000000
26     26   6.24331000  19.477160000
2

In [10]:
str(data)

'data.frame':	3000 obs. of  3 variables:
 $ X : int  1 2 3 4 5 6 7 8 9 10 ...
 $ V1: num  2.07 17.94 1.08 11.12 23.71 ...
 $ V2: num  -3.24 15.78 7.32 14.41 2.56 ...


In [1]:
#using dput() and dump()

In [2]:
y <- data.frame(a = 1, b = "a")

In [3]:
dput(y)

structure(list(a = 1, b = structure(1L, .Label = "a", class = "factor")), .Names = c("a", 
"b"), row.names = c(NA, -1L), class = "data.frame")


In [4]:
y

a b
1 1 a

In [5]:
dput(y, file = "y.R")

In [6]:
new.y <- dget("y.R")

In [7]:
new.y

a b
1 1 a

In [8]:
x <- "foo"

In [9]:
y <- data.frame(a = 1L, b = "a")

In [13]:
dump(c("x", "y"), file = "data.R")

In [14]:
rm(x, y)

In [18]:
source("data.R")

In [20]:
str(y)

'data.frame':	1 obs. of  2 variables:
 $ a: int 1
 $ b: Factor w/ 1 level "a": 1


In [21]:
#binary format

In [22]:
a <- data.frame(x = rnorm(100), y = runif(100))

In [25]:
b <- c(3, 4.4, 1 / 3)

In [26]:
save(a, b, file = "mydata.rda")

In [29]:
Load("mydata.rda")

ERROR: Error in eval(expr, envir, enclos): could not find function "Load"


In [30]:
#Using Textual and Binary Formats for Storing Data

In [31]:
x <- list(1, 2, 3)

In [32]:
serialize(x, NULL)

 [1] 58 0a 00 00 00 02 00 03 03 02 00 02 03 00 00 00 00 13 00 00 00 03 00 00 00
[26] 0e 00 00 00 01 3f f0 00 00 00 00 00 00 00 00 00 0e 00 00 00 01 40 00 00 00
[51] 00 00 00 00 00 00 00 0e 00 00 00 01 40 08 00 00 00 00 00 00

In [33]:
#file connection

In [51]:
con <- file("datasets/cluster/xclara.csv")

In [46]:
print(con)

                  description                         class 
"datasets/cluster/xclara.csv"                        "file" 
                         mode                          text 
                          "r"                        "text" 
                       opened                      can read 
                     "closed"                         "yes" 
                    can write 
                        "yes" 


In [52]:
open(con, "r")

In [53]:
close(con)

In [54]:
#Reading Lines of a Text File

In [57]:
con <- file("datasets/cluster/xclara.csv")

In [58]:
x <- readLines(con, 10)

In [59]:
x

[1] "\"\",\"V1\",\"V2\""       "\"1\",2.072345,-3.241693"
 [3] "\"2\",17.93671,15.78481"  "\"3\",1.083576,7.319176" 
 [5] "\"4\",11.12067,14.40678"  "\"5\",23.71155,2.557729" 
 [7] "\"6\",24.16993,32.02478"  "\"7\",21.66578,4.892855" 
 [9] "\"8\",4.693684,12.34217"  "\"9\",19.21191,-1.121366"

In [60]:
#Reading From a URL Connection

In [74]:
# con <- url("http://www.jhsph.edu", "r")

In [75]:
# x <- readLines(con)

In [76]:
# head(x)

In [77]:
#########

In [78]:
#subsetting vector

In [79]:
x <- c("a", "b", "c", "c", "d", "a")

In [80]:
x[1]

[1] "a"

In [81]:
x[2:4]

[1] "b" "c" "c"

In [82]:
x[c(1, 3, 4)]

[1] "a" "c" "c"

In [1]:
#subsetting matrix

In [2]:
x <- matrix(1:6, 2,3)

In [4]:
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [5]:
x[1, 2]

[1] 3

In [6]:
x[2,2]

[1] 4

In [7]:
x[1,]

[1] 1 3 5

In [8]:
x[,1]

[1] 1 2

In [9]:
x[2,]

[1] 2 4 6

In [10]:
x[,2]

[1] 3 4

In [11]:
#Dropping matrix dimensions

In [12]:
x <- matrix(1:6, 2, 3)

In [14]:
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [13]:
x[1,2]

[1] 3

In [18]:
x[1, 2, drop = FALSE]

[,1]
[1,] 3

In [19]:
print(x)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [20]:
#Subsetting Lists

In [25]:
x <- list(foo = 1:4, bar = 0.6)

In [26]:
print(x)

$foo
[1] 1 2 3 4

$bar
[1] 0.6



In [27]:
x[1]

$foo
[1] 1 2 3 4

In [28]:
x["bar"]

$bar
[1] 0.6

In [29]:
x$bar

[1] 0.6

In [30]:
x$foo

[1] 1 2 3 4

In [31]:
#Subsetting Nested Elements of a List

In [32]:
x <- list(a = list(10, 12, 14), b = c(3.14, 2.81))

In [35]:
x

$a
$a[[1]]
[1] 10

$a[[2]]
[1] 12

$a[[3]]
[1] 14


$b
[1] 3.14 2.81

In [34]:
x[[c(1, 3)]]

[1] 14

In [36]:
x[[1]][[3]]

[1] 14

In [37]:
x[[c(2, 1)]]

[1] 3.14